insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (1, '밀키트1', 12000, 14, current_timestamp, '맛있다', 15.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (2, '밀키트2', 13000, 10, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (3, '밀키트3', 15000, 9, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (4, '밀키트4', 12000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (5, '밀키트5', 22000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (6, '밀키트6', 23000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (7, '밀키트7', 9000, 32, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (8, '밀키트8', 11000, 10, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (9, '밀키트9', 21000, 15, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (10, '밀키트10', 43000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (11, '밀키트11', 8000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (12, '밀키트12', 6000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (13, '밀키트13', 17000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (14, '밀키트14', 12000, 30, current_timestamp,'나쁘지않다', 20.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (15, '밀키트15', 19000, 30, current_timestamp, '맛있다', 15.0);
insert into product(id, name, price, stockamount, createdTime, detail, discountRate) values (16, '밀키트16', 22000, 30, current_timestamp, '맛있다', 15.0);
